# Generated by Django 4.1.3 on 2022-11-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Titulo')),
                ('subtitle', models.CharField(default='', max_length=100, verbose_name='Subtitulo')),
                ('body', models.TextField(default='', max_length=500, verbose_name='Mensagem')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(default='', max_length=500, verbose_name='Adicionar Comentário')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('thread', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.thread')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['created'],
            },
        ),
    ]
